# Dispatch of jobs triggered by slash commands
name: Slash command dispatch

on:
  issue_comment:
    types: [created]

jobs:
  command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/slash-command-dispatch@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          issue-type: pull-request
          event-type-suffix: -command
          dispatch-type: workflow
          commands: |
            update-cmor-cvs-table
            update-stac-json
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}

      - name: Update comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            **Errors:**

            ${{ steps.scd.outputs.error-message }}
